version: '2'

services:
  mqtt-message-broker:
    image: tellu/rsd-mqtt-broker:latest
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - gatewaynet

#   prometheus:
#     image: prom/prometheus
#     restart: unless-stopped
#     logging:
#       driver: json-file
#       options:
#         max-size: 10m
#     command: --storage.tsdb.retention.time=6w
#       --config.file=/etc/prometheus/prometheus.yml
#       --storage.tsdb.path=/prometheus
#       --web.console.libraries=/usr/share/prometheus/console_libraries
#       --web.console.templates=/usr/share/prometheus/consoles
#     ports:
#       - 9090:9090
#     volumes:
#       - /etc/tellugw/prometheus.yml:/etc/prometheus/prometheus.yml
#       - /var/prometheus:/prometheus
#     networks:
#       - gatewaynet

#   node-red:
#     image: nodered/node-red
#     restart: unless-stopped
#     logging:
#       driver: json-file
#       options:
#         max-size: 10m
#     ports:
#       - 1880:1880
#     networks:
#       - gatewaynet

#   network-agent:
#     image: rdautov/network-agent:1.0.1
#     restart: unless-stopped
#     logging:
#       driver: json-file
#       options:
#         max-size: 10m
#     networks:
#       - gatewaynet

#   prometheus-agent:
#     image: rdautov/prometheus:1.0.1
#     restart: unless-stopped
#     logging:
#       driver: json-file
#       options:
#         max-size: 10m
#     #command: --network host
#     network_mode: host
    
# networks:
#   gatewaynet:
#     driver: bridge
# #    ipam:
# #      driver: default
# #      config:
# #        - subnet: 192.168.100.0/24
# #          gateway: 192.168.100.1
# #          ip_range: 192.168.100.1/24
