gateways:
    hosts:
        ENACTGW001:
            ansible_ssh_host: 10.0.0.9
    vars:
        ansible_become: yes
        ansible_ssh_user: pi
        ansible_ssh_private_key_file: ./private-files/ssh-key-gateway-enact
        ansible_ssh_pass: raspberry
